#!/usr/bin/env bash
# Configures Nginx with custom X-Served-By header
# shellcheck disable=SC2154

apt-get update -y
apt-get install -y nginx

HOSTNAME=$(hostname)

sed -i "s/^\tserver_name _;/\tserver_name _;\n\tadd_header X-Served-By $HOSTNAME;/" \
    /etc/nginx/sites-available/default

service nginx restart
