#!/usr/bin/env bash
# Configures a web server to add a custom HTTP response header
# shellcheck disable=SC2154

sudo apt-get -y update
sudo apt-get -y install nginx

sudo sed -i '/listen 80 default_server;/a \ \tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

sudo service nginx restart
