#!/usr/bin/env bash
# Installs and configures HAProxy with round-robin

apt-get update -y
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

cat > /etc/haproxy/haproxy.cfg << 'HAPROXY'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7036-web-01 54.147.35.15:80 check
    server 7036-web-02 44.204.91.237:80 check
HAPROXY

service haproxy restart

